### ISSUE TITLE
Add pop up to Onboarding Landing Page

### ISSUE THREAD

**Issue by golmek** [golemfactory/onboarding#109]
We need following cookie/privacy pop up on Landing Page so it is similar to main golem page:

![Image](https://github.com/golemfactory/onboarding_staging/assets/126684244/d700aa2f-4d41-4ffa-9650-d3243bf71353)

**Acceptance Criteria:**
- Pop up is showing up on Onboarding Landing Page
- Pop up behaves the same way as on main Golem Page
- Link do Cookie Policy: https://www.golem.network/cookie-policy
- Privacy Policy link: https://www.golem.network/privacy

**Comment by pociej** [comment]
solved using cookieyes
