### ISSUE TITLE
verify ramp workflow

### ISSUE THREAD

**Issue by pociej** [golemfactory/onboarding#110]
currently it seems that we can use even production ramp keys in eny environmetn. Make sure its ok from legal point of view. 

Example scenarion : 

User takes our onbording and hosts it using our keys. Or even take our keys and render ramp widget somewhere.

**Comment by golmek** [comment]
Based on: https://support.ramp.network/en/articles/13064-ramp-integration-api-keys-explained 
It should be safe to put RAMP API keys on frontend:
<img width="709" alt="SCR-20240312-jexi" src="https://github.com/golemfactory/onboarding_staging/assets/126684244/20202d9f-8444-4862-a0e4-9d3fca3ef8a0">

However, I will double verify that with RAMP too.

**Comment by golmek** [comment]
Communication to RAMP sent. Waiting for reponse

**Comment by golmek** [comment]
Got the response from RAMP, which confirms that it is safe to use API key on Frontend:



![Image](https://github.com/golemfactory/onboarding_staging/assets/126684244/7ab20083-e356-4955-9c6f-8aa4796ba4c6)
