### ISSUE TITLE
Provide proper redirection on landing page

### ISSUE THREAD

**Issue by pociej** [golemfactory/onboarding#86]
...for use cases on landing page.

**Comment by golmek** [comment]
![Image](https://github.com/golemfactory/onboarding_staging/assets/126684244/23f6e3e7-b535-4fba-af44-c3a58fa62e32)


1. https://www.golem.network/
2. proceed to next step of onboarding

**Comment by golmek** [comment]
![Image](https://github.com/golemfactory/onboarding_staging/assets/126684244/3baaf57f-51c5-438c-9da6-6dd0243d57d8)

3. https://docs.golem.network/docs/creators/dapps
4. https://docs.golem.network/docs/creators/ray
5. https://docs.golem.network/docs/creators

**Comment by golmek** [comment]
![Image](https://github.com/golemfactory/onboarding_staging/assets/126684244/82e910c2-6fca-4a4d-9668-b4a9a5e5789e)

6. https://github.com/golemfactory/golem-kernel-python
7. proceed to next step of onboarding
8. https://www.golem.network/

**Comment by pociej** [comment]
@golmek missing links for finish step in case of user without yagna
